{
 "title": "smartctl Disk Errors",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "client",
    "label": "Server Name",
    "query": {
     "query": "label_values(smartprom_smartctl_exit_status,instance)"
    }
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(smartprom_smartctl_exit_status,drive)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "disk overview for $client",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "smartprom_smart_status_passed{instance=\"$client\"}"
    },
    {
     "expr": "smartprom_scsi_grown_defect_list{instance=\"$client\"}"
    },
    {
     "expr": "smartprom_scsi_error_counter_log_read_total_uncorrected_errors{instance=\"$client\"}"
    },
    {
     "expr": "smartprom_scsi_error_counter_log_write_total_uncorrected_errors{instance=\"$client\"}"
    },
    {
     "expr": "smartprom_scsi_error_counter_log_verify_total_uncorrected_errors{instance=\"$client\"}"
    }
   ]
  },
  {
   "title": "Specific Device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "$device on $client",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "smartprom_smart_status_passed{instance=\"$client\", drive=\"$device\"}"
      }
     ]
    },
    {
     "title": "SCSI error counter for $device on $client",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "smartprom_scsi_error_counter_log_read_errors_corrected_by_eccfast{instance=\"$client\", drive=\"$device\"}",
       "legendFormat": "Read errors corrected by eccfast"
      },
      {
       "expr": "smartprom_scsi_error_counter_log_read_errors_corrected_by_eccdelayed{instance=\"$client\", drive=\"$device\"}",
       "legendFormat": "Read errors corrected by eccdelayed"
      },
      {
       "expr": "smartprom_scsi_error_counter_log_read_errors_corrected_by_rereads_rewrites{instance=\"$client\", drive=\"$device\"}",
       "legendFormat": "Read errors corrected by rereads rewrites"
      },
      {
       "expr": "smartprom_scsi_error_counter_log_read_correction_algorithm_invocations{instance=\"$client\", drive=\"$device\"}",
       "legendFormat": "Read correction invocations"
      },
      {
       "expr": "smartprom_scsi_error_counter_log_write_errors_corrected_by_eccfast{instance=\"$client\", drive=\"$device\"}",
       "legendFormat": "Write errors corrected by eccfast"
      },
      {
       "expr": "smartprom_scsi_error_counter_log_write_errors_corrected_by_eccdelayed{instance=\"$client\", drive=\"$device\"}",
       "legendFormat": "Write errors corrected by eccdelayed"
      },
      {
       "expr": "smartprom_scsi_error_counter_log_write_errors_corrected_by_rereads_rewrites{instance=\"$client\", drive=\"$device\"}",
       "legendFormat": "Write errors corrected by rereads rewrites"
      },
      {
       "expr": "smartprom_scsi_error_counter_log_write_correction_algorithm_invocations{instance=\"$client\", drive=\"$device\"}",
       "legendFormat": "Write correction invocations"
      },
      {
       "expr": "smartprom_scsi_error_counter_log_verify_errors_corrected_by_eccfast{instance=\"$client\", drive=\"$device\"}",
       "legendFormat": "Verify errors corrected by eccfast"
      },
      {
       "expr": "smartprom_scsi_error_counter_log_verify_errors_corrected_by_eccdelayed{instance=\"$client\", drive=\"$device\"}",
       "legendFormat": "Verify errors corrected by eccdelayed"
      },
      {
       "expr": "smartprom_scsi_error_counter_log_verify_errors_corrected_by_rereads_rewrites{instance=\"$client\", drive=\"$device\"}",
       "legendFormat": "Verify errors corrected by rereads rewrites"
      },
      {
       "expr": "smartprom_scsi_error_counter_log_verify_correction_algorithm_invocations{instance=\"$client\", drive=\"$device\"}",
       "legendFormat": "Verify correction invocations"
      }
     ]
    },
    {
     "title": "Error Processed for $device on $client",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "expr": "smartprom_scsi_error_counter_log_read_gigabytes_processed{instance=\"$client\", drive=\"$device\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "smartprom_scsi_error_counter_log_write_gigabytes_processed{instance=\"$client\", drive=\"$device\"}",
       "legendFormat": "Write"
      },
      {
       "expr": "smartprom_scsi_error_counter_log_verify_gigabytes_processed{instance=\"$client\", drive=\"$device\"}",
       "legendFormat": "Verify"
      }
     ]
    }
   ]
  }
 ]
}